-- Hipodromo
INSERT INTO hipodromo(nombre, direccion) VALUES ('Hipodromo de La Plata', 'Av. 44 esq. 116');
INSERT INTO hipodromo(nombre, direccion) VALUES ('Hipodromo de San Isidro', 'Av. Márquez 504');
INSERT INTO hipodromo(nombre, direccion) VALUES ('Hipodromo de Palermo', 'Av. del Libertador 4101');

-- Pista
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 1', 'Hipodromo de La Plata', 'Arena', 11);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 2', 'Hipodromo de La Plata', 'Arena', 12);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 3', 'Hipodromo de La Plata', 'Arena', 18);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 4', 'Hipodromo de La Plata', 'Arena', 11);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 5', 'Hipodromo de San Isidro', 'Césped', 11);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 6', 'Hipodromo de San Isidro', 'Arena', 11);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 7', 'Hipodromo de Palermo', 'Césped', 9);
INSERT INTO pista(nombre, hipodromo_nombre, tipo, nro_andariveles) VALUES ('Pista 8', 'Hipodromo de Palermo', 'Arena', 11);

-- Stud
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('CAITO', 'verde claro', 'verde claro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('MAM', 'naranja', 'naranja');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('GAUCHITO GIL', 'amarillo', 'amarillo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('B.J.(Vguay.)', 'violeta', 'violeta');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('GENTE DE TURF', 'rojo', 'rojo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('VAS-QUITO', 'celeste', 'celeste');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LOS GATEADOS (MDP)', 'gris oscuro', 'gris oscuro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('HARAS LAS EMMAS', 'rosado', 'rosado');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('PASO LOPEZ (Azul)', 'azul oscuro', 'azul oscuro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('MOZO BACAN', 'gris claro', 'gris claro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('FEDEX (Azul)', 'azul claro', 'azul claro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('EL NEGRO', 'negro', 'negro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('DON LEOPOLDO', 'rojo amarillo', 'rojo amarillo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('JUBAFER', 'azul verde violeta', 'azul verde');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('EL MAXI', 'azul negro', 'azul negro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('EL PADRINO', 'verde amarillo', 'verde amarillo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LAS TUTIS', 'violeta celeste', 'violeta celeste');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('CABO ALARCON', 'rosa rojo naranja', 'rosa rojo naranja');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('NOE MAR', 'verde amaraillo azul', 'verde amaraillo azul');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LOS COLORADOS', 'rojo', 'rojo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('FIRMAMENTO', 'gris verde azul', 'gris verde azul');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('BEVA-ALCA', 'blanco amarillo rojo negro', 'blanco amarillo rojo negro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LOS HERMANITOS (S.Fe)', 'violeta blanco azul', 'violeta blanco azul');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('EL GUASO', 'gris verde granate', 'gris verde granate');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LA CHUMBEADA', 'marron amarillo', 'marron amarillo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LOS 4 ASES', 'azul marron gris', 'azul marron gris');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LA CAMPANA', 'blanco gris negro', 'blanco gris negro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LA QUEBRADA', 'negro marron claro verde', 'negro marron claro verde');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('CUMENEYEN', 'verde amarello', 'verde amarello');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('CUCUNITO', 'azul celeste amarillo blanco', 'azul celeste amarillo blanco');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('EL ZAINO', 'verde claro', 'verde claro y rojo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('VALLE DE LA LUNA', 'gris azul claro', 'gris azul claro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('ESEERREEFE', 'verde oscuro', 'verde oscuro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('MIRABELLA', 'amarillo rojo', 'rojo amarillo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('L.A. (LP)', 'verde celeste amarillo', 'verde celeste amarillo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LE FRAGOLE', 'verde celeste naranja', 'verde celeste naranja');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LA PROVIDENCIA', 'marron naranja', 'marron naranja');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('ASAYE', 'rojo celeste', 'rojo celeste');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('27 DE ABRIL', 'blanco rojo', 'blanco rojo');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('PINO SOLO', 'rojo naranja blanco', 'rojo naranja blanco');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('QUEREUQUEN', 'verde violeta negro', 'verde violeta negro');
INSERT INTO stud(nombre, color_gorra, color_chaqueta) VALUES ('LINDA SIEMPRE', 'marron celesete', 'marron celesete');

-- Persona
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000001, 'Juan Carlos', 'Perez', 'CAITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000002, 'Jose', 'Picardo', 'CAITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000003, 'Jimena', 'Cleveland', 'CAITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000004, 'Gerardo', 'Paez', 'MAM');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000005, 'Juan', 'Picolo', 'MAM');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000006, 'Monto', 'Remz', 'MAM');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000007, 'Moises', 'Agers', 'GAUCHITO GIL');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000008, 'Mariano', 'Andre', 'GAUCHITO GIL');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000009, 'German', 'Agata', 'GAUCHITO GIL');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000010, 'Joseph', 'Wevver', 'B.J.(Vguay.)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000011, 'Aaron', 'Crispulo', 'B.J.(Vguay.)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000012, 'Abrahan', 'Cleveland', 'B.J.(Vguay.)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000013, 'Bonfilio', 'Webbez', 'GENTE DE TURF');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000014, 'Boris', 'Mica', 'GENTE DE TURF');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000015, 'Caesar', 'Tasptger', 'GENTE DE TURF');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000016, 'Bertoldo', 'Cullen', 'VAS-QUITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000017, 'Briccio', 'Pacet', 'VAS-QUITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000018, 'Caetano', 'Cuadragesimo', 'VAS-QUITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000019, 'Caian', 'Cupido', 'LOS GATEADOS (MDP)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000020, 'Cain', 'Crispulo', 'LOS GATEADOS (MDP)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000021, 'Mauricio', 'Cuniberto', 'LOS GATEADOS (MDP)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000022, 'Miguel', 'Mirac', 'HARAS LAS EMMAS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000023, 'Guillermo', 'Locars', 'HARAS LAS EMMAS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000024, 'Juan', 'Cyrus', 'HARAS LAS EMMAS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000025, 'Hernan', 'Legiers', 'PASO LOPEZ (Azul)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000026, 'Calepodio', 'Lopez', 'PASO LOPEZ (Azul)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000027, 'Hashini', 'Cynric', 'PASO LOPEZ (Azul)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000028, 'Aaron', 'Cleveland', 'MOZO BACAN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000029, 'Abrahan', 'Cuyen', 'MOZO BACAN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000030, 'Subar', 'Cupido', 'MOZO BACAN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000031, 'Tabia', 'Yumiz', 'FEDEX (Azul)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000032, 'Baltasar', 'Crispulo', 'FEDEX (Azul)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000033, 'Ricardo', 'Ferdinando', 'FEDEX (Azul)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000034, 'Richard', 'Fernandez', 'EL NEGRO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000035, 'Abel', 'Galo', 'EL NEGRO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000036, 'Roberto', 'Kiriff', 'EL NEGRO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000037, 'Mercucio', 'Pignato', 'DON LEOPOLDO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000038, 'Flavio', 'Pignato', 'DON LEOPOLDO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000039, 'Baltasar', 'Crispulo', 'DON LEOPOLDO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000040, 'Faustino', 'Paulot', 'JUBAFER');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000041, 'Bertoldo', 'Feliciano', 'JUBAFER');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000042, 'Fermal', 'Cleveland', 'JUBAFER');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000043, 'Pocho', 'Paulot', 'EL MAXI');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000044, 'Beranger', 'Pocur', 'EL MAXI');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000045, 'Tatin', 'Felicisimo', 'EL MAXI');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000046, 'Tomas', 'Flinn', 'EL PADRINO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000047, 'Barrett', 'Firneo', 'EL PADRINO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000048, 'Lucas', 'Fintano', 'EL PADRINO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000049, 'Calixto', 'Crispulo', 'LAS TUTIS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000050, 'Benedicto', 'Ferreolo', 'LAS TUTIS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000051, 'Abel', 'Fiacro', 'LAS TUTIS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000052, 'Calixto', 'Filindo', 'CABO ALARCON');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000053, 'Lucas', 'Fileas', 'CABO ALARCON');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000054, 'Aaron', 'Corbett', 'CABO ALARCON');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000055, 'Camden', 'Cleveland', 'NOE MAR');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000056, 'Mauricio', 'Perez', 'NOE MAR');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000057, 'Abrahan', 'Rodriguez', 'NOE MAR');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000058, 'Sebastian', 'Florian', 'LOS COLORADOS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000059, 'Santiago', 'Rodriguez', 'LOS COLORADOS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000060, 'Abrahan', 'Febronio', 'LOS COLORADOS');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000061, 'Fabian', 'Floviano', 'FIRMAMENTO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000062, 'Mariano', 'Faustiniano', 'FIRMAMENTO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000063, 'Federico', 'Corbett', 'FIRMAMENTO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000064, 'Andres', 'Rodriguez', 'BEVA-ALCA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000065, 'Baltasar', 'Perez', 'BEVA-ALCA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000066, 'Sergio', 'Cooper', 'BEVA-ALCA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000067, 'Fernando', 'Perez', 'LOS HERMANITOS (S.Fe)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000068, 'Federico', 'Perez', 'LOS HERMANITOS (S.Fe)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000069, 'Abel', 'Coriolano', 'LOS HERMANITOS (S.Fe)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000070, 'Carlos', 'Perez', 'EL GUASO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000071, 'Federico', 'Perez', 'EL GUASO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000072, 'Fabian', 'Mirato', 'EL GUASO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000073, 'Fernando', 'Coriolano', 'LA CHUMBEADA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000074, 'Carlos', 'Morza', 'LA CHUMBEADA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000075, 'Fernando', 'Miguez', 'LA CHUMBEADA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000076, 'Facundo', 'Cleveland', 'LOS 4 ASES');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000077, 'Permacio', 'Molar', 'LOS 4 ASES');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000078, 'Claudiano', 'Raes', 'LOS 4 ASES');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000079, 'Pablo', 'Rico', 'LA CAMPANA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000080, 'Baltasar', 'Rolon', 'LA CAMPANA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000081, 'Julian', 'Mecrano', 'LA CAMPANA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000082, 'German', 'Paset', 'LA QUEBRADA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000083, 'Carlos', 'Pocara', 'LA QUEBRADA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000084, 'Petrin', 'Olvert', 'LA QUEBRADA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000085, 'James', 'Merca', 'CUMENEYEN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000086, 'Sebastian', 'Mujica', 'CUMENEYEN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000087, 'Rodrigo', 'Monitz', 'CUMENEYEN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000088, 'Aaron', 'Cleveland', 'CUCUNITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000089, 'Alberto', 'Licsd', 'CUCUNITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000090, 'Abel', 'Tradec', 'CUCUNITO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000091, 'Patricio', 'Totiz', 'EL ZAINO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000092, 'Juan Carlos', 'Pera', 'EL ZAINO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000093, 'Jorge', 'Banquito', 'EL ZAINO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000094, 'Matias', 'Farrell', 'VALLE DE LA LUNA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000095, 'Abundio', 'Licrec', 'VALLE DE LA LUNA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000096, 'Charlie', 'Clotario', 'VALLE DE LA LUNA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000097, 'Climaco', 'Marts', 'ESEERREEFE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000098, 'Clicerio', 'Clinio', 'ESEERREEFE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000099, 'Baltasar', 'Faraon', 'ESEERREEFE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000100, 'Claudiano', 'Argesty', 'MIRABELLA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000101, 'Cleto', 'Mirabella', 'MIRABELLA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000102, 'Clero', 'Mirabella', 'MIRABELLA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000103, 'Cleon Adriano', 'Reo', 'L.A. (LP)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000104, 'Cleon', 'Estud', 'L.A. (LP)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000105, 'Cirineo', 'Pertac', 'L.A. (LP)');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000106, 'Christos', 'Rodriguez', 'LE FRAGOLE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000107, 'Chukwuma', 'Rodriguez', 'LE FRAGOLE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000108, 'Chase', 'Perez', 'LE FRAGOLE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000109, 'Camden', 'Cochi', 'LA PROVIDENCIA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000110, 'Cesario', 'Farnacio', 'LA PROVIDENCIA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000111, 'Carlisle', 'Coleman', 'LA PROVIDENCIA');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000112, 'Celestino', 'Faraj', 'ASAYE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000113, 'Abundio', 'Cochi', 'ASAYE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000114, 'Carlos', 'Fantino', 'ASAYE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000115, 'Celestino', 'Fairfax', '27 DE ABRIL');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000116, 'Ceferino', 'Falcon', '27 DE ABRIL');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000117, 'Abundio', 'Clinio', '27 DE ABRIL');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000118, 'Castor', 'Cooper', 'PINO SOLO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000119, 'Adriano', 'Clotario', 'PINO SOLO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000120, 'Caspar', 'Cooper', 'PINO SOLO');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000121, 'Adriano', 'Fairfax', 'QUEREUQUEN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000122, 'Carmelo', 'Clinio', 'QUEREUQUEN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000123, 'Casandro', 'Cooper', 'QUEREUQUEN');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000124, 'Abundio', 'Clotario', 'LINDA SIEMPRE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000125, 'Carmelo', 'Coleman', 'LINDA SIEMPRE');
INSERT INTO persona(dni, nombres, apellidos, stud_nombre) VALUES (10000126, 'Carlos', 'Cochi', 'LINDA SIEMPRE');
